theme = "my-nord"

[editor]
auto-pairs = false
line-number = "relative"
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
# word-completion = true
# word-completion-trigger-length = 5
# rounded-corners = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "version-control", "spinner"]
center = ["file-name", "file-modification-indicator"]
right = ["register", "diagnostics", "selections", "position-percentage", "total-line-numbers"]

# [editor.whitespace.render]
# space = "all"
# nbsp = "all"
# nnbsp = "all"
# tab = "all"
# newline = "none"

# :set whitespace.render all defaults to the items below.
# [editor.whitespace.characters]
# nbsp = "⍽"
# nnbsp = "␣"
# space = "·"
# tab = "→"
# tabpad = "·" # Tabs will look like "→···" (depending on tab width)
# newline = "⏎"
 
[keys.normal]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
'#' = 'toggle_comments'
a = ['append_mode', 'collapse_selection']
w = 'move_next_sub_word_start'
W = 'move_next_word_start'
b = 'move_prev_sub_word_start'
B = 'move_prev_word_start'
e = 'move_next_sub_word_end'
E = 'move_next_word_end'
X = 'select_line_above'
# d and c yank by default. Ick.
d = "delete_selection_noyank"
c = "change_selection_noyank"
A-d = "delete_selection"
A-c = "change_selection"
# Both of these could pop the paste once paste stack is working.
#C-j = ["extend_to_line_bounds", ":set-next-register a", "delete_selection", ":set-next-register a", "paste_after"]
#C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
#p = 'paste_after'
#P = 'paste_before'
#A-p = 'paste_picker_after'

# [keys.select]
# W = 'extend_next_sub_word_start'
# B = 'extend_prev_sub_word_start'
# E = 'extend_next_sub_word_end'
#

[keys.insert]
S-tab = "move_parent_node_start"

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
