# [[language]]
# name = "__common__"
# scope = "source.__common__"
# file-types = []
# language-servers = [ "ltex-ls-plus", "merge-conflict-assistant" ]

# [[language]]
# name = "txt"
# scope = "source.txt"
# injection-regex = "txt"
# file-types = ["txt"]
# shebangs = []
# comment-token = "#"
# language-servers = [ "merge-assistant" ]

[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 100           # set max completion results len for each group: words, snippets, unicode-input
feature_words = true                 # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = false                # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)

# write logs to /tmp/completion.log
# [language-server.scls.environment]
# RUST_LOG = "info,simple-completion-language-server=info"
# LOG_FILE = "scls-completion.log"

[language-server.ltex-ls-plus.config]
ltex.enabled = ['html', 'markdown', 'org', 'python', 'rust', 'restructuredtext']

[[language]]
name = "rust"
auto-format = true
language-servers = [ "rust-analyzer", "codebook", "merge-conflict-assistant" ]

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "python"
auto-format = false
language-servers = [ "pylsp", "codebook", "merge-conflict-assistant" ]

[[language]]
name = "fish"
indent = { tab-width = 4, unit = " " }
language-servers = [ "fish-lsp", "codebook", "merge-conflict-assistant" ]

[language-server.fish-lsp]
command = "fish-lsp"
args = ["start"]

[language-server.merge-conflict-assistant]
command = "merge-conflict-assistant"
# args = ["--debug"]

[[language]]
name = "bash"
indent = { tab-width = 4, unit = " " }
language-servers = [ "bash-language-server", "codebook", "merge-conflict-assistant" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "markdown-oxide", "codebook", "merge-conflict-assistant" ]

[[language]]
name = "tcl"
file-types = [ "tcl", "expect" ]
shebangs = [ "tclsh", "tclish", "jimsh", "wish", "expect" ]

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "merge-conflict-assistant" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "merge-conflict-assistant" ]

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "merge-conflict-assistant" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "merge-conflict-assistant" ]

[[language]]
name = "json"
language-servers = [ "vscode-json-language-server", "merge-conflict-assistant" ]
